# Generated by Django 3.0.1 on 2020-02-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=256)),
                ('score', models.IntegerField(default=1)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Category')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('moto', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='houses')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('mail', models.CharField(default='user@example.com', max_length=100)),
                ('security', models.BooleanField(default=False)),
                ('ninja', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('G', 'Player'), ('P', 'Pensia'), ('Z', 'Zombie'), ('H', 'Hanzaha'), ('T', 'Testing')], default='G', max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users')),
                ('houses', models.ManyToManyField(related_name='Dworkin', to='index.House')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
    ]
