# Generated by Django 3.0.1 on 2020-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
