# Generated by Django 3.0.1 on 2020-02-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200224_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.CharField(default='', max_length=256),
        ),
    ]
