# Generated by Django 3.0.1 on 2020-02-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_user_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('G', 'Player'), ('P', 'Pensioner'), ('Z', 'Zombie'), ('C', 'Commemoration'), ('T', 'Testing')], default='G', max_length=1),
        ),
    ]
