# Generated by Django 3.0.1 on 2020-09-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20200925_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='primary_color',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='house',
            name='secondary_color',
            field=models.CharField(default='', max_length=9),
        ),
    ]
