# Generated by Django 3.0.1 on 2020-09-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200925_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='house',
            name='secondary_color',
        ),
        migrations.AddField(
            model_name='house',
            name='back_color',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='house',
            name='nav_color',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='house',
            name='title_color',
            field=models.CharField(default='', max_length=8),
        ),
    ]
