# Generated by Django 3.0.1 on 2020-09-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20200925_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='text_color',
            field=models.CharField(default='', max_length=8),
        ),
    ]
