# Generated by Django 3.0.1 on 2020-09-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_house_footer_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='back_color',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='house',
            name='footer_color',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='house',
            name='headers_color',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='house',
            name='nav_color',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='house',
            name='text_color',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='house',
            name='title_color',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
