# Generated by Django 3.0.1 on 2020-09-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20200926_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='deadline',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
