# Generated by Django 3.1.1 on 2021-02-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_game_gamerank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=2048)),
                ('ordering_id', models.IntegerField(default=-1)),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.page')),
            ],
        ),
    ]
